name: Build Android APK

on: [push]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython==0.29.36
    
    # Accept Android SDK licenses before building
    - name: Accept Android SDK licenses
      run: |
        mkdir -p $HOME/.android
        echo "android.sdk.path=$HOME/.buildozer/android/platform/android-sdk" >> $HOME/.android/default.properties
        yes | sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk --licenses || true
    
    - name: Build APK
      run: |
        buildozer android debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk
        retention-days: 30
